"""create_room

Revision ID: 2b185c5743d9
Revises: 3f77fd5ead4d
Create Date: 2026-05-17 01:22:50.672513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b185c5743d9'
down_revision: Union[str, Sequence[str], None] = '3f77fd5ead4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sqlmodel.AutoString(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('status', sa.Enum('vacant', 'occupied', 'maintenance', name='roomstatus'), nullable=False),
    sa.Column('elec_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_property_id'), 'room', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_room_property_id'), table_name='room')
    op.drop_table('room')
    op.execute(sa.text("DROP TYPE IF EXISTS roomstatus"))
