"""add_unique_room_number_per_property

Revision ID: 48d0bd101bc5
Revises: 66ccdebacec7
Create Date: 2026-05-17 04:12:27.471613

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '48d0bd101bc5'
down_revision: Union[str, Sequence[str], None] = '66ccdebacec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_room_property_room_number', 'room', ['property_id', 'room_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_property_room_number', 'room', type_='unique')
    # ### end Alembic commands ###
