"""add unique constraint property user name and varchar lengths

Revision ID: 7fe9e659fa8e
Revises: a7b8c9d0e1f2
Create Date: 2026-05-23 23:49:49.963322

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7fe9e659fa8e"
down_revision: Union[str, Sequence[str], None] = "a7b8c9d0e1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_property_user_name", "property", ["clerk_user_id", "name"]
    )
    op.drop_index(
        op.f("ix_shared_meter_reading_meter_id"), table_name="shared_meter_reading"
    )
    op.drop_constraint(
        op.f("uq_shared_meter_reading_meter_period"),
        "shared_meter_reading",
        type_="unique",
    )
    op.create_index(
        op.f("ix_shared_meter_reading_shared_meter_id"),
        "shared_meter_reading",
        ["shared_meter_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shared_meter_reading_shared_meter_id"),
        table_name="shared_meter_reading",
    )
    op.create_unique_constraint(
        op.f("uq_shared_meter_reading_meter_period"),
        "shared_meter_reading",
        ["shared_meter_id", "period"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_shared_meter_reading_meter_id"),
        "shared_meter_reading",
        ["shared_meter_id"],
        unique=False,
    )
    op.drop_constraint("uq_property_user_name", "property", type_="unique")
    # ### end Alembic commands ###
