"""add bank fields to property

Revision ID: e27f095a9cf0
Revises: f6a7b8c9d0e1
Create Date: 2026-05-18 22:40:48.682754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e27f095a9cf0'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_meter_room')
    op.drop_index(op.f('ix_shared_meter_reading_meter_id'), table_name='shared_meter_reading')
    op.drop_table('shared_meter_reading')
    op.drop_index(op.f('ix_shared_meter_property_id'), table_name='shared_meter')
    op.drop_table('shared_meter')
    op.drop_constraint(op.f('uq_invoice_contract_period'), 'invoice', type_='unique')
    op.drop_index(op.f('ix_invoice_public_token'), table_name='invoice')
    op.create_index(op.f('ix_invoice_public_token'), 'invoice', ['public_token'], unique=False)
    op.add_column('property', sa.Column('bank_account_no', sqlmodel.AutoString(length=30), nullable=True))
    op.add_column('property', sa.Column('bank_name', sqlmodel.AutoString(length=100), nullable=True))
    op.add_column('property', sa.Column('bank_holder', sqlmodel.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'bank_holder')
    op.drop_column('property', 'bank_name')
    op.drop_column('property', 'bank_account_no')
    op.drop_index(op.f('ix_invoice_public_token'), table_name='invoice')
    op.create_index(op.f('ix_invoice_public_token'), 'invoice', ['public_token'], unique=True)
    op.create_unique_constraint(op.f('uq_invoice_contract_period'), 'invoice', ['contract_id', 'period'], postgresql_nulls_not_distinct=False)
    op.create_table('shared_meter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('shared_meter_property_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_meter_pkey'))
    )
    op.create_index(op.f('ix_shared_meter_property_id'), 'shared_meter', ['property_id'], unique=False)
    op.create_table('shared_meter_reading',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shared_meter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('prev_reading', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('curr_reading', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_prev_auto', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shared_meter_id'], ['shared_meter.id'], name=op.f('shared_meter_reading_shared_meter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_meter_reading_pkey')),
    sa.UniqueConstraint('shared_meter_id', 'period', name=op.f('uq_shared_meter_reading_meter_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shared_meter_reading_meter_id'), 'shared_meter_reading', ['shared_meter_id'], unique=False)
    op.create_table('shared_meter_room',
    sa.Column('shared_meter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('shared_meter_room_room_id_fkey')),
    sa.ForeignKeyConstraint(['shared_meter_id'], ['shared_meter.id'], name=op.f('shared_meter_room_shared_meter_id_fkey')),
    sa.PrimaryKeyConstraint('shared_meter_id', 'room_id', name=op.f('shared_meter_room_pkey'))
    )
    # ### end Alembic commands ###
